import Image from "next/image";
import Link from "next/link";

export const metadata = {
  title: "Pokemon detail page",
  description: "Generated by create next app",
};

// async function getPokemon(pokemonId) {
//   const res = await fetch(`https://api.example.com/artist/${pokemonId}`);
//   return res.json();
// }

export default async function Home() {
  // const artistData = getPokemon(pokemonId);
  // Initiate the request

  // Albums Component
  // const albums = await promise;
  // Wait for the albums promise to resolve

  return (
    <div>
      {/* <ul>
        {albums.map((album) => (
          <li key={album.id}>{album.name}</li>
        ))}
      </ul> */}

      <div>Hello</div>
      <div>this is the Pokemon detail page</div>
      <div>
        Display name, image, height, weight, classification, type, weakness, and
        resistance of the Pokemon.
      </div>
      <div>
        Include a button to open a popup showing the Pokemon's evolutions.
      </div>
      <div>
        Query evolution data only when the button is clicked, not beforehand.
        Refer to https://www.pokemon.com/us/pokedex/bulbasaur for an example of
        a Pokemon detail page.
      </div>
      <div>
        Statically render the detail pages for the first 20 Pokemon at build
        time.
      </div>
      <div>GraphQL implmentaion</div>
    </div>
  );
}
